moai:
  initialized: true
  initialized_at: '2025-12-19T00:00:00Z'
  version: 1.7.0
project:
  name: claude-craft
  mode: personal
  description: ''
  created_at: '2026-01-20 09:54:53'
  optimized: false
  template_version: 1.7.0
